---
title: "Set de problemas 2"
subtitle: "Introducción a Mínimos Cuadrados Ordinarios"
author: "Econometría I"
date: "<br>A entregar el miércoles 22 de setiembre"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

```{R, setup, include = F}
# Packages
library(pacman)
p_load(
  ggplot2, gridExtra, ggthemes, latex2exp, kableExtra,
  tidyverse, broom, knitr, magrittr
)
# Colors
red_pink <- "#e64173"
turquoise <- "#20B2AA"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
# Themes
theme_axes_y <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.y = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_x <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.x = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 11))
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  warning = F,
  message = F
)
```

Se presenta el primer práctico de Econometría I. El mismo trata conceptos introductorios de Mínimos Cuadrados Ordinarios.

.hi-pink[**Regla general de los prácticos:**] La entrega debe realizarse en un archivo .pdf realizado con cualquier programa de computadora (MS Word, Open Office, $\LaTeX$ o letra a mano .hi-pink[prolija y legible]. A su vez, en caso de emplear __.mono[R]__, se debe enviar el archivo .R correspondiente.

El nombre del archivo debe contener los **apellidos de los integrantes del grupo (únicamente)** y debe ser enviado al siguiente correo: .pink[ppereda@correo.um.edu.uy]. Esperar confirmación de recepción. Grupos de tres o menos integrantes.

## Problema 1

Se desea estimar una función de producción utilizando datos de 23 empresas mediante el método de mínimos cuadrados (MCO).  $Y_i$ es el logaritmo del PBI, $X_{2i}$ es el logaritmo del capital y $X_{3i}$ es el logaritmo del trabajo.

$$Y_{i}=\beta_{1}+\beta_{2} X_{2 i}+\beta_{3} X_{3 i}+\varepsilon_{i}$$

Se tiene la siguiente información en forma de desvíos con respecto a la media:

$$\begin{array}{c}
\sum_{i=1}^{23} x_{3 i}^{2}=12; \ \sum_{i=1}^{23} x_{2 i}^{2}=12; \ \sum_{i=1}^{23} y_{i}^{2}=10 \\
\sum_{i=1}^{23} x_{3 i} * x_{2 i}=8; \ \sum_{i=1}^{23} y_{i} * x_{3 i}=10; \ \sum_{i=1}^{23} y_{i} * x_{2 i}=8
\end{array}$$

en donde:

$$y_{i}=\left(Y_{i}-\bar{Y}\right) ; \ x_{2 i}=\left(X_{2 i}-\bar{X}_{2}\right); \ x_{3 i}=\left(X_{3 i}-\bar{X}_{3}\right)$$

**1a.** Estime los coeficientes $\beta_2$, $\beta_3$ y sus errores estándar.

**1b.** Interprete los resultados obtenidos y analice su significancia estadística.

**1c.** Calcule el $R^2$ y el $R^2$ corregido. Comente los resultados obtenidos.


## Problema 2

Suponga que se dispone del siguiente modelo para estimar el valor de una casa:

$$y_{i}=\beta_{1}+\beta_{2} x_{i 2}+\beta_{3} x_{i 3}+\beta_{4} x_{i 3}^{2}+u_{i}$$
En donde $y$ es el valor de la casa, $x_2$ es una medida de tamaño de la casa y $x_3$ representa la distancia de la casa al centro de la ciudad.

---
class: clear

Se dispone de los siguientes datos:

| $y$ <br>(valor) | $x_2$ <br>(tamaño) | $x_3$<br>(distancia) |
|:------------:|:---------------:|:------------------:|
|      345     |       1650      |         3.5        |
|      238     |       1870      |         0.5        |
|      452     |       2230      |         1.5        |
|      422     |       1740      |         4.5        |
|      328     |       1900      |         1.8        |
|      375     |       2000      |         0.1        |
|      660     |       3200      |         3.4        |
|      466     |       1860      |         3.0        |
|      290     |       1230      |         1.0        |

**2a.** Escriba el modelo en forma matricial. Defina las siguientes matrices: $Y$, $\beta$, $X$, $X’$, $(X’X)$ y $X’Y$. 

**2b.** Estime dicho modelo mediante el método de mínimos cuadrados ordinarios. Calcule la matriz de varianzas y covarianzas.

**2c.** Interprete los coeficientes estimados.   

**2d.** Estime los coeficientes utilizando .mono[R]. Adjunte la salida de .mono[R].

## Problema 3

Se considera un modelo de regresión lineal simple $y_i = \beta x_i + \mu_i$. Suponga se cumplen los supuestos del modelo de regresión lineal.

Se pide:

**3a.** Obtener un estimador de $\beta$ como solución al problema de minimización de los cuadrados de los residuos. 

**3b.** Obtener la esperanza y varianza del estimador indicando la aplicación de los supuestos.


## Problema 4

**4a.** Pruebe que la suma de cuadrados de residuos (SCR) asociada al estimador de mínimos cuadrados de $\beta$ puede escribirse como $SCR=Y^{T} Y-\hat{Y}^{T} \hat{Y}$

**4b.** Comente. Un investigador estimo un modelo de regresión lineal y el $R^2$ fue - 0,32. ¿Es posible? ¿Hay un error en las cuentas?

**4c.** Demuestre que $R^2$ es el cuadrado del coeficiente de correlación entre la variable dependiente, $y$ y su valor predicho, $\hat y$.  


