---
title: "Set de problemas 1"
subtitle: "Repaso e introducción a R"
author: "Econometría I"
date: "<br>A entregar el sábado 28 de agosto."
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

```{R, setup, include = F}
# Packages
library(pacman)
p_load(
  ggplot2, gridExtra, ggthemes, latex2exp, kableExtra,
  tidyverse, broom, knitr, magrittr
)
# Colors
red_pink <- "#e64173"
turquoise <- "#20B2AA"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
# Themes
theme_axes_y <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.y = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_x <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.x = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 11))
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  warning = F,
  message = F
)
```

Se presenta el primer práctico de Econometría I. El mismo trata conceptos básicos de matemáticas, probabilidad, estadística y cálculo matricial. Se recomienda leer los apéndices A, B, C y D de _Jeffrey M. Wooldridge. Introductory Econometrics: A Modern Approach, 5th Edition_ y [los capítulos 2 y 3](https://www.econometrics-with-r.org/2-pt.html) de _Hanck, Arnold, Gerber y Schmelzer. Introduction to Econometrics with R_.

.hi-pink[**Regla general de los prácticos:**] La entrega debe realizarse en un archivo .pdf realizado con cualquier programa de computadora (MS Word, Open Office, $\LaTeX$ o letra a mano .hi-pink[prolija y legible]. A su vez, en caso de emplear __.mono[R]__, se debe enviar el archivo .R correspondiente.

El archivo debe contener los apellidos de los integrantes del grupo y debe ser enviado al siguiente correo: .pink[ppereda@correo.um.edu.uy]. Esperar confirmación de recepción. Grupos de tres o menos integrantes.

## Problema 1

Considerando la siguiente tabla que contiene el gasto mensual en vivienda para 12 familias:

| Familia | Gasto mensual en <br>vivienda (en U$S) |
|---------|----------------------------------------|
| 1       |                   300                  |
| 2       |                   550                  |
| 3       |                   350                  |
| 4       |                  1100                  |
| 5       |                   640                  |
| 6       |                   480                  |
| 7       |                   450                  |
| 8       |                   700                  |
| 9       |                   670                  |
| 10      |                   600                  |
| 11      |                  1900                  |
| 12      |                  5200                  |

**1a.** Encuentre el gasto mensual promedio y mediano.

**1b.** Indique el rango intercuartílico, el desvío estándar y la varianza.

**1c.** Suponga que la familia número 12 aumenta su gasto mensual en un 50%, pero los de todas las demás familias permanecen fijos. Calcule nuevamente los puntos anteriores. Se puede utilizar __.mono[mutate]__ junto a la función __.mono[if_else]__.

---
class: clear

**1d.** Comente brevemente las medidas de media y mediana. ¿En qué situaciones estas medidas difieren de forma relevante?

**Nota** Los datos de la tabla se pueden leer desde [aquí](https://raw.githubusercontent.com/paulapereda/Econometria/master/data/gasto_mensual_vivienda.csv) en caso de querer trabajarlos desde .mono[R].

## Problema 2

Sea $\bar{Y}$ el promedio muestral de una variable aleatoria con media $\mu$ y varianza $\sigma^{2}$. Considere dos estimadores alternativos de $\mu$: $W_{1}=\frac{n-1}{n} \cdot \bar{Y}$ y $W_{2}=\frac{\bar{Y}}{2}$.

**2a.** Demuestre que $W_1$ y $W_2$ son dos estimadores sesgados de $\mu$ y encuentre sus sesgos. ¿Qué sucede con los sesgos a medida que $n \rightarrow \infty$?

**2b.** Encuentre los límites de probabilidad de $W_1$ y $W_2$ (sugerencia: utilice las propiedades PLIM1 y PLIM2 del Wooldridge, apéndice C, para $W_1$ observe que $\operatorname{plim}\left[\frac{n}{n-1}\right]=1$). ¿Son consistentes los estimadores?

**2c.** Encuentre $\operatorname{Var}\left(W_{1}\right)$ y $\operatorname{Var}\left(W_{2}\right)$.


## Problema 3

Suponga que en una universidad grande el promedio de calificaciones, $GPA$ y de puntuaciones $SAT$ están relacionados por la esperanza condicional $\mathrm{E}(\mathrm{GPA} / \mathrm{SAT})=0.7+0.001 \mathrm{SAT}$.

**3a.** Encuentre la esperanza de $GPA$ cuando $SAT = 800$ y $\mathrm{E}(\mathrm{GPA} / \mathrm{SAT = 1400})$. Comente la diferencia.

**3b.** Si el $SAT$ promedio de los alumnos de esta universidad es 1100, ¿cuál es el $GPA$? (Sugerencia: aplique la propiedad CE4, Wooldridge apéndice B).




